name: "SCPSL.PluginListing"
description: "Generates listing for all releases."
branding:
  icon: file
  color: blue
inputs:
  token:
    description: "Github Token."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--token"
    - ${{ inputs.token }}
